//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsClient.SimpleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SimpleService.ISimpleService")]
    public interface ISimpleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetEvenNumbers", ReplyAction="http://tempuri.org/ISimpleService/GetEvenNumbersResponse")]
        int[] GetEvenNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetEvenNumbers", ReplyAction="http://tempuri.org/ISimpleService/GetEvenNumbersResponse")]
        System.Threading.Tasks.Task<int[]> GetEvenNumbersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetOddNumbers", ReplyAction="http://tempuri.org/ISimpleService/GetOddNumbersResponse")]
        int[] GetOddNumbers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISimpleService/GetOddNumbers", ReplyAction="http://tempuri.org/ISimpleService/GetOddNumbersResponse")]
        System.Threading.Tasks.Task<int[]> GetOddNumbersAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISimpleServiceChannel : WindowsFormsClient.SimpleService.ISimpleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SimpleServiceClient : System.ServiceModel.ClientBase<WindowsFormsClient.SimpleService.ISimpleService>, WindowsFormsClient.SimpleService.ISimpleService {
        
        public SimpleServiceClient() {
        }
        
        public SimpleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SimpleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SimpleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int[] GetEvenNumbers() {
            return base.Channel.GetEvenNumbers();
        }
        
        public System.Threading.Tasks.Task<int[]> GetEvenNumbersAsync() {
            return base.Channel.GetEvenNumbersAsync();
        }
        
        public int[] GetOddNumbers() {
            return base.Channel.GetOddNumbers();
        }
        
        public System.Threading.Tasks.Task<int[]> GetOddNumbersAsync() {
            return base.Channel.GetOddNumbersAsync();
        }
    }
}
